site_name: 'Cloud Native Developers JP - ハンズオンチュートリアル'
repo_name: 'cndjp/tutorials'
repo_url: 'https://github.com/cndjp/tutorials'
theme:
    name: material
    palette:
        primary: 'teal'
        accent: 'teal'
    language: 'ja'
    logo:
        icon: 'cloud'
markdown_extensions:
    - admonition
    - codehilite:
        linenums: false
    - def_list
    - fontawesome_markdown
    - footnotes
    - toc:
        permalink: true
extra:
    search:
        language: 'en, jp'
    social:
        - type: 'github'
          link: 'https://github.com/cndjp'
extra_css:
    - 'https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css'
    - 'stylesheets/extra.css'
pages:
    - Home: index.md
    - Kubernetesの基礎:
        - 最初のアプリケーションを動かしてみる: 'documents/kubernetes-basics/play-with-bootcamp-app.md'
    - ローカルクラスターの作成:
        - Vagrant CoreOS Cluster: 'documents/create-local-cluster/vagrant-coreos-cluster.md'
